version: '3.8'

services:
  dt_server:
    image: dt_server:latest
    build: .
    container_name: dt_server
    ports:
      - "${SERVER_PORT:-8081}:${SERVER_PORT:-8081}"
    environment:
      - SERVER_PORT=${SERVER_PORT:-8081}
    network_mode: "bridge"
    restart: always
    working_dir: /app/dt_server/deploy
    command: ["/bin/bash", "-c", "./run.sh -p ${SERVER_PORT:-8081}"]
