server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: digital-twin-websocket-server
  
  # RabbitMQ配置
  rabbitmq:
    # host: localhost
    # port: 5672
    # username: guest
    # password: guest
    # virtual-host: /

    host: umi.xyz
    port: 5672
    username: thingsboard
    password: Aa20250815!
    virtual-host: /
    
    # 连接池配置
    connection-timeout: 15000
    requested-heartbeat: 30
    
    # 监听器配置
    listener:
      simple:
        concurrency: 1
        max-concurrency: 1
        prefetch: 1
        acknowledge-mode: manual
        default-requeue-rejected: false
        
  # Jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
      
  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # MySQL数据库配置
  datasource:
    url: jdbc:mysql://umi.xyz:3306/dt_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dt
    password: Aa20250815!
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
# TDengine配置
tdengine:
  url: jdbc:TAOS-RS://umi.xyz:6041/digital_twin
  username: thingsboard
  password: Aa20250815!
  
opcua:
  config:
    gatewayId: ${GATEWAY_ID:b3238480-7db4-11f0-9b31-5b91814762c3}
    serverUrl: ${SERVER_URL:https://thingsboard.umi.xyz}
    username: ${OPC_USERNAME:tenant@thingsboard.org}
    password: ${OPC_PASSWORD:Aa20250815!}

# 日志配置
logging:
  level:
    com.digitaltwin.websocket: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.amqp: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/digital-twin-websocket.log

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# SpringDoc OpenAPI配置
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  show-actuator: true

# 外部认证配置
external:
  auth:
    url: http://your-auth-server.com/api/authenticate

# MinIO配置
minio:
  endpoint: http://umi.xyz:9000
  access-key: thingsboard
  secret-key: Aa20250815!
  bucket-name: digital-twin-files
  region: us-east-1
    
# 自定义配置
alarm:
  # 告警防重复时间间隔（分钟）
  duplicate-prevention-minutes: 60

trail:
  history:
    cache:
      # 缓存过期时间（毫秒），默认30分钟
      expire-after-write: 1800000
      # 缓存最大条目数，默认1000
      maximum-size: 10

websocket:
  # 主题配置
  topics:
    sensor-data: /topic/sensor-data
    heartbeat: /topic/heartbeat
  
  # 队列配置
  queues:
    sensor-data: sensor.data.queue